### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by jax-parker** [jax-parker/kayak-app#16]
As a *user* I can *view the nav bar from all pages* so I can *navigate easily between pages*

**Acceptance criteria**

- A Navbar consists of the following icons (Home , Sign in, Sign up)
- The Navbar has effects
- The header has a custom Logo.

**Tasks**

- [x]  Add a component directory, and a NavBar.js file inside.
- [x]  Inside NavBar.js, create functional component, add navbar, use react bootstrap classes to customize.
- [x]  Add CSS style module for both App and NavBar components.
- [x] Add routing and wireup links in Nav.js

.
