### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by jax-parker** [jax-parker/kayak-app#17]
As a *user* I can *create an account* so I can *have full-access to all features.*

**Acceptance**
User creates an account and redirected to the main page

**Tasks**

- [x] Connect to api

- [x]  Create and add Signup styles in SignInUpForm.module.css.
- [x]  Create a new page SignUpForm.
- [x]  Create a SignInForm
- [x] Context hook 
- [x] Create Axios Interceptors
- [x] Burger toggle hook
