### ISSUE TITLE
Ability To Manage Profile

### ISSUE THREAD

**Issue by jax-parker** [jax-parker/kayak-app#20]
As a *registered use*r, I can *edit my profile*, so I can *update my information*.

**Acceptance criteria**
Profile is editable, avatar can be changed, new information can be added.

**Tasks**

- [x] Create ProfileEditForm file, create form of all input fields that relate to the Profile model
- [x] Define a hook that handle changes being done to the form input field
- [x] Define a hook that handle submit of the form, this is done by appending the new values to the related object field.
