### ISSUE TITLE
Create A Launchsite

### ISSUE THREAD

**Issue by jax-parker** [jax-parker/kayak-app#21]
As a *logged in user* I can *create a post about a kayak launch site* so *other users can see if a launch is of interest to them*

**Acceptance criteria**
User can write and submit adventures posts, which include content and an image.

**Tasks**

- [x] Create a new js file PostCreateForm , hold the form inputs with hooks that handle the inputs.
- [x] Send post data to API & add error alerts
- [ ] Create style file , hold the css roles that reflect nice UI
- [x] Add url to the Navbar.js
