### ISSUE TITLE
Extend Profile Model

### ISSUE THREAD

**Issue by jax-parker** [jax-parker/kayak-app#22]
**Acceptance criteria**
User can fill in personal information

**Tasks**

- [x] Extend the profileEditForm.js
- [x] Extend the related form by adding those as inputs.
- [x] Extend the profilePage.js to add those fields to be shown as a part of the info about the User.
